src/pages/index.css
src/pages/index.tsx
src/theme.css

fix: layout of 2 or 3 columns if filter column is shown

---

src/pages/index.css
src/pages/index.tsx
src/theme.css

* fix: layout of 2 or 3 columns if filter column is shown
* fix: change two and three columns layout

fix: layout of 2 or 3 columns if filter column is shown (#107)

---

src/pages/index.css
src/pages/index.tsx
src/theme.css

fix: layout three columns in trending cards

---

src/entities/Event/routes/updateEvent.ts
src/entities/Slack/utils.ts

Feat: notify rejection into slack

---

src/pages/submit.css
src/pages/submit.tsx

Related to #166 
Also in #168 changed the ToggleBox title from tag to category

feat: change labels from tag to category in submit and edit

---

src/context/ProfileSetting.tsx
src/hooks/useListEventsFiltered.ts

feat: use local time as default for not signed users

---

src/components/Event/EventModal/EventDetail/EventDetail.css
src/components/Event/EventModal/EventDetail/EventDetail.tsx
src/components/MenuIcon/MenuIcon.css
src/components/MenuIcon/MenuIcon.tsx
src/hooks/useEventEditor.ts
src/pages/submit.tsx

feat: clone event. Add new component MenuIcon

---

gatsby-browser.js
package-lock.json
package.json
src/components/Layout/CarouselEvents/CarouselEvents.css
src/components/Layout/CarouselEvents/CarouselEvents.tsx
src/components/Layout/ListEvents/ListEvents.css
src/components/Layout/ListEvents/ListEvents.tsx
src/components/Layout/Navigation.tsx
src/components/Layout/TrendingEvents/TrendingEvents.css
src/components/Layout/TrendingEvents/TrendingEvents.tsx
src/context/Category.tsx
src/context/Event.tsx
src/entities/Schedule/model.ts
src/entities/Schedule/utils.ts
src/intl/en.json
src/modules/events.ts
src/modules/locations.ts
src/pages/index.css
src/pages/index.tsx
src/pages/schedule.tsx
src/pages/submit.tsx

- Refactor index splitting in CarouselEvents, TrendingEvents and ListEvents components
- Merge schedule with current branch
- Create the schedule tab

Feat: pride event re-design

---

package-lock.json
package.json
src/components/Event/CarouselEvents/CarouselEvents.tsx
src/server.ts

| current | new |
|--------|------|
| <img width="1239" alt="Screenshot 2023-03-20 at 11 29 00" src="https://user-images.githubusercontent.com/208789/226371130-78d42172-6770-4992-98fe-3cdd540de8a4.png"> | <img width="1163" alt="Screenshot 2023-03-20 at 11 27 03" src="https://user-images.githubusercontent.com/208789/226370686-aa1069a5-ddb5-4a5a-96c9-f123d229e5ac.png"> |

fix: replace carousel

---

src/theme.css

fix: two column margins

---

package-lock.json
package.json

Reverts decentraland/events#537

Revert "feat: update decentraland-gatsby with places submenu in navbar"

---

Pulumi.website-events-dev.yml
Pulumi.website-events-prd.yml
src/components/Event/EventModal/EventDetail/EventDetail.tsx
src/config/dev.json
src/config/local.json
src/config/prod.json
src/entities/Event/utils.ts
src/modules/features.ts

This PR links the Profile site with the Events site.

feat: Link Profile with Events

---

src/components/Layout/Navigation.css
src/theme.css

fix: scroll on tabs

---

package-lock.json
package.json
src/components/Layout/UserMenu.tsx
src/entities/Event/routes/createEvent.ts
src/entities/Notification/sender.ts
src/entities/Schedule/routes.ts

This PR removes the FF on the new navbar and updates `decentraland-gatsby` to add tracking to it.

fix: Add tracking to the UserInformation component

---

src/api/Places.ts
src/config/dev.json
src/config/local.json
src/config/prod.json

As the places API will be loaded from its own domain, split the two urls.

fix: Split places api and url

---

Dockerfile

This PR adds the cleaning phase to the build process to avoid problems with the asset paths.

fix: Clean before building

---

.gitignore
Dockerfile
src/server.ts

Set new rollout as default rollout

feat: always use new rollout

---

package-lock.json
package.json

feat: update dcl gatsby

---

src/server.ts

This PR changes the CORS origin so the events site and API can be used from these specific origins.

feat: Configure CORS origin

---

src/intl/en.json

feat: update image recommended label

---

src/hooks/useListEventsFiltered.ts

fix: Homepage type filters did the same for every type

---

src/entities/Event/types.ts
src/entities/Event/utils.ts
src/intl/en.json
src/pages/submit/index.tsx

fix: Calculate only new recurrent dates

---

src/entities/Event/routes/updateEvent.ts

fix: Only validate if change on update
